"""Generate Data/domain_context.json from Data/schedule_master_v1.csv.

Single source of truth for domain vocabulary (equipment tag prefixes and
locations) that Module 1 (normalizer) and Module 2 (extractor) both need.
Run this whenever schedule_master_v1.csv changes; it is NOT part of the
per-report pipeline and does not touch shared/schemas.py.

Usage:
    python scripts/generate_domain_context.py
    python scripts/generate_domain_context.py --schedule path/to/other.csv --out path/to/out.json

Also writes/overwrites Engine/module_2_extraction/config/locations.json
directly (via --write-locations, on by default) so the extractor needs no
code change to pick up new locations. Set --no-write-locations to skip
that and only emit domain_context.json.
"""

from __future__ import annotations

import argparse
import csv
import json
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SCHEDULE = REPO_ROOT / "Data" / "schedule_master_v1.csv"
DEFAULT_OUT = REPO_ROOT / "Data" / "domain_context.json"
DEFAULT_LOCATIONS_JSON = REPO_ROOT / "Engine" / "module_2_extraction" / "config" / "locations.json"

# Matches a leading letter-prefix on an equipment tag, e.g. "SP-101" -> "SP",
# "F101" -> "F". Mirrors the tag shape used throughout schedule_master_v1.csv.
_TAG_PREFIX_RE = re.compile(r"^([A-Za-z]+)-?\d")


def extract_prefixes(schedule_path: Path) -> list[str]:
    prefixes: dict[str, int] = {}
    unparsed: list[str] = []

    with schedule_path.open("r", encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            tag = (row.get("equipment_tag") or "").strip()
            if not tag:
                continue
            match = _TAG_PREFIX_RE.match(tag)
            if match:
                prefix = match.group(1).upper()
                prefixes[prefix] = prefixes.get(prefix, 0) + 1
            else:
                unparsed.append(tag)

    if unparsed:
        print(f"WARNING: {len(unparsed)} equipment_tag values did not match the "
              f"expected <letters><digits> shape and were skipped: {unparsed[:10]}"
              + (" ..." if len(unparsed) > 10 else ""))

    # Longest-first so the regex built from these tries multi-letter
    # prefixes (e.g. "TT", "SP") before single-letter ones (e.g. "T").
    return sorted(prefixes, key=lambda p: (-len(p), p))


def extract_locations(schedule_path: Path) -> list[str]:
    locations: set[str] = set()
    with schedule_path.open("r", encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            loc = (row.get("location") or "").strip()
            if loc:
                locations.add(loc)
    # Longest-first, matching the sort extract_locations() in extractor.py
    # already does at runtime -- harmless duplication, keeps the emitted
    # file readable/diffable on its own.
    return sorted(locations, key=lambda l: (-len(l), l))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--schedule", type=Path, default=DEFAULT_SCHEDULE,
                         help="Path to schedule_master_v1.csv")
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT,
                         help="Path to write domain_context.json")
    parser.add_argument("--locations-json", type=Path, default=DEFAULT_LOCATIONS_JSON,
                         help="Path to Module 2's locations.json")
    parser.add_argument("--no-write-locations", action="store_true",
                         help="Skip overwriting locations.json; only emit domain_context.json")
    args = parser.parse_args()

    if not args.schedule.exists():
        raise SystemExit(f"Schedule file not found: {args.schedule}")

    prefixes = extract_prefixes(args.schedule)
    locations = extract_locations(args.schedule)

    domain_context = {
        "_generated_from": str(args.schedule.relative_to(REPO_ROOT)) if args.schedule.is_relative_to(REPO_ROOT) else str(args.schedule),
        "_note": "Auto-generated by scripts/generate_domain_context.py. Do not hand-edit; re-run the script instead.",
        "equipment_tag_prefixes": prefixes,
        "locations": locations,
    }

    args.out.parent.mkdir(parents=True, exist_ok=True)
    with args.out.open("w", encoding="utf-8") as f:
        json.dump(domain_context, f, indent=2)
        f.write("\n")
    print(f"Wrote {args.out} — {len(prefixes)} equipment prefixes, {len(locations)} locations")
    print(f"  prefixes: {prefixes}")
    print(f"  locations: {locations}")

    if not args.no_write_locations:
        args.locations_json.parent.mkdir(parents=True, exist_ok=True)
        with args.locations_json.open("w", encoding="utf-8") as f:
            json.dump({"locations": locations}, f, indent=2)
            f.write("\n")
        print(f"Wrote {args.locations_json} (Module 2 locations config, regenerated from schedule)")


if __name__ == "__main__":
    main()